### ISSUE TITLE
Problem with generateInstCat

### ISSUE THREAD

**Issue by TomGlanzman** [LSSTDESC/DC2_Repo#135]
A number of instanceCatalog failures occurred this evening as Run 1.1p production ramps up.  Is this a bug in the generator code, or is this an I/O bottleneck?  I am suspicious about the need to lock a file. 
Here is an example output:

```
Tue Feb 20 20:32:49 PST 2018
$ /usr/bin/time generateInstCat.py --db /global/projecta/projectdirs/lsst/groups/SSim/DC2/minion_1016_desc_dithered_v4.db --agn_db_name /global/projecta/projectdirs/lsst/groups/SSim/DC2/agn_db_mbh_7.0_m_i_30.0.sqlite --descqa_catalog protoDC2 --fov 2.1 --protoDC2_ra 55.064 --protoDC2_dec -29.783 --enable_sprinkler --min_mag 10.0 --out_dir /global/cscratch1/sd/descpho/Pipeline-tasks/DC2-phoSim-3_WFD-r/000111/instCat --ids 250408

/global/common/software/lsst/common/miniconda/py3-4.3.21/lib/python3.6/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sims_catalogs/2.5.0.sims/python/lsst/sims/catalogs/db/dbConnection.py:553: UserWarning: Duplicate object type id 4 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sims_catalogs/2.5.0.sims/python/lsst/sims/catalogs/db/dbConnection.py:553: UserWarning: Duplicate object type id 28 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
WARNING: ErfaWarning: ERFA function "utcut1" yielded 1 of "dubious year (Note 3)" [astropy._erfa.core]
/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sims_catUtils/2.5.0.sims+1/python/lsst/sims/catUtils/mixins/VariabilityMixin.py:852: RuntimeWarning: divide by zero encountered in true_divide
  dd = _au_to_parsec/parallax
Traceback (most recent call last):
  File "/global/common/software/lsst/cori-haswell-gcc/sims_GCRCatSimInterface/sims_GCRCatSimInterface-0.1.1/bin/generateInstCat.py", line 51, in 
    instcat_writer.write_catalog(obsHistID, out_dir=args.out_dir, fov=args.fov)
  File "/global/common/software/lsst/cori-haswell-gcc/sims_GCRCatSimInterface/sims_GCRCatSimInterface-0.1.1/python/desc/sims/GCRCatSimInterface/InstanceCatalogWriter.py", line 327, in write_catalog
    write_header=False)
  File "/global/common/software/lsst/cori-haswell-gcc/sims_GCRCatSimInterface/sims_GCRCatSimInterface-0.1.1/python/desc/sims/GCRCatSimInterface/TwinklesClasses.py", line 89, in write_catalog
    dbo = dboClass()
  File "/global/common/software/lsst/cori-haswell-gcc/sims_GCRCatSimInterface/sims_GCRCatSimInterface-0.1.1/python/desc/sims/GCRCatSimInterface/DatabaseEmulator.py", line 220, in __init__
    gc = GCRCatalogs.load_catalog(yaml_file_name, config_overwrite)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21/lib/python3.6/site-packages/GCRCatalogs/register.py", line 169, in load_catalog
    return load_catalog_from_config_dict(config)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21/lib/python3.6/site-packages/GCRCatalogs/register.py", line 120, in load_catalog_from_config_dict
    BaseGenericCatalog)(**catalog_config)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21/lib/python3.6/site-packages/GCR.py", line 60, in __init__
    self._subclass_init(**kwargs)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21/lib/python3.6/site-packages/GCRCatalogs/alphaq.py", line 81, in _subclass_init
    with h5py.File(self._file, 'r') as fh:
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21/lib/python3.6/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21/lib/python3.6/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (Unable to lock file, errno = 524, error message = 'unknown error 524')
146.08user 38.38system 18:28.22elapsed 16%CPU (0avgtext+0avgdata 1760112maxresident)k
0inputs+45952outputs (78major+778603minor)pagefaults 0swaps
```

**Comment by yymao** [comment]
@TomGlanzman see if this fixes it:
```bash
export HDF5_USE_FILE_LOCKING=FALSE     
```
Ref: http://www.nersc.gov/users/data-analytics/data-management/i-o-libraries/hdf5-2/h5py/#toc-anchor-6

**Comment by TomGlanzman** [comment]
@yymao thanks, I put in that change a few minutes after you posted and that particular problem seems to have gone away.  Will close this issue.  Thanks again!
