### ISSUE TITLE
Problem with simultaneous database access in generateInstCat

### ISSUE THREAD

**Issue by TomGlanzman** [LSSTDESC/DC2_Repo#136]
Running more than just a few instances (~25) of the generateInstCat.py script at NERSC, I am seeing failures of this kind:

sqlite3.OperationalError: disk I/O error

If this is a bottleneck, perhaps we need to install some/all parts of this system onto the $SCRATCH disk?

A full log of a failed run follows:
```
Tue Feb 20 22:06:53 PST 2018
$ /usr/bin/time generateInstCat.py --db /global/projecta/projectdirs/lsst/groups/SSim/DC2/minion_1016_desc_dithered_v4.db --agn_db_name /global/projecta/projectdirs/lsst/groups/SSim/DC2/agn_db_mbh_7.0_m_i_30.0.sqlite --descqa_catalog protoDC2 --fov 2.1 --protoDC2_ra 55.064 --protoDC2_dec -29.783 --enable_sprinkler --min_mag 10.0 --out_dir /global/cscratch1/sd/descpho/Pipeline-tasks/DC2-phoSim-3_WFD-r/000210/instCat --ids 451456

/global/common/software/lsst/common/miniconda/py3-4.3.21/lib/python3.6/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sims_catalogs/2.5.0.sims/python/lsst/sims/catalogs/db/dbConnection.py:553: UserWarning: Duplicate object type id 4 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sims_catalogs/2.5.0.sims/python/lsst/sims/catalogs/db/dbConnection.py:553: UserWarning: Duplicate object type id 28 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
WARNING: ErfaWarning: ERFA function "utcut1" yielded 1 of "dubious year (Note 3)" [astropy._erfa.core]
/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sims_catUtils/2.5.0.sims+1/python/lsst/sims/catUtils/mixins/VariabilityMixin.py:852: RuntimeWarning: divide by zero encountered in true_divide
  dd = _au_to_parsec/parallax
Traceback (most recent call last):
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/common/software/lsst/cori-haswell-gcc/sims_GCRCatSimInterface/sims_GCRCatSimInterface-0.1.1/bin/generateInstCat.py", line 51, in 
    instcat_writer.write_catalog(obsHistID, out_dir=args.out_dir, fov=args.fov)
  File "/global/common/software/lsst/cori-haswell-gcc/sims_GCRCatSimInterface/sims_GCRCatSimInterface-0.1.1/python/desc/sims/GCRCatSimInterface/InstanceCatalogWriter.py", line 327, in write_catalog
    write_header=False)
  File "/global/common/software/lsst/cori-haswell-gcc/sims_GCRCatSimInterface/sims_GCRCatSimInterface-0.1.1/python/desc/sims/GCRCatSimInterface/TwinklesClasses.py", line 176, in write_catalog
    write_mode=write_mode)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sims_catalogs/2.5.0.sims/python/lsst/sims/catalogs/definitions/CompoundInstanceCatalog.py", line 297, in _write_compound
    for chunk in master_results:
  File "/global/common/software/lsst/cori-haswell-gcc/sims_GCRCatSimInterface/sims_GCRCatSimInterface-0.1.1/python/desc/sims/GCRCatSimInterface/DatabaseEmulator.py", line 140, in __next__
    return self._descqa_obj._postprocess_results(chunk)
  File "/global/common/software/lsst/cori-haswell-gcc/sims_GCRCatSimInterface/sims_GCRCatSimInterface-0.1.1/python/desc/sims/GCRCatSimInterface/ProtoDC2DatabaseEmulator.py", line 295, in _postprocess_results
    chunk_size=1000000)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sims_catalogs/2.5.0.sims/python/lsst/sims/catalogs/db/dbConnection.py", line 491, in get_arbitrary_chunk_iterator
    return self.get_chunk_iterator(query, chunk_size = chunk_size, dtype = dtype)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sims_catalogs/2.5.0.sims/python/lsst/sims/catalogs/db/dbConnection.py", line 505, in get_chunk_iterator
    return ChunkIterator(self, query, chunk_size, arbitrarySQL = True)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sims_catalogs/2.5.0.sims/python/lsst/sims/catalogs/db/dbConnection.py", line 78, in __init__
    self.exec_query = dbobj.connection.session.execute(query)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1023, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/global/common/software/lsst/cori-haswell-gcc/stack/w.2018.03_py3/stack/miniconda3-4.3.21-10a4fa6/Linux64/sqlalchemy/1.0.8.lsst3+4/lib/python/SQLAlchemy-1.0.8-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error [SQL: 'SELECT galaxy_id, magNorm, varParamStr FROM agn_params WHERE galaxy_id BETWEEN 5069 AND 2531517 ORDER BY galaxy_id']
```

**Comment by jchiang87** [comment]
This is a problem with multiple processes trying to access `/global/projecta/projectdirs/lsst/groups/SSim/DC2/agn_db_mbh_7.0_m_i_30.0.sqlite` at the same time.  One approach would be to stage this file locally for each visit.  Aside from that, I doubt there is an easy fix to make in the instance catalog generation code.

**Comment by rbiswas4** [comment]
Does this mean `sqlite` does not queue multiple processes trying to access a table? Or this creating some kind of race condition because of the queuing. From the IO error it would seem that it is the first.

@jbkalmbach @danielsf This seems to arise at the stage where it looks for agn parameters.

**Comment by TomGlanzman** [comment]
According to this [faq](https://www.sqlite.org/faq.html#q5), there should be no software limitation on read access (I am assuming that there is no writing happening).  I am thinking this may be an I/O overload on the r/w GPFS file system at NERSC.   We have been advised to keep critical files either in the r/o GPFS area (common/software) or in the Lustre $SCRATCH area.

This particular file is 214MB in size so it could be staged as Jim suggests.  How would I specify the location of that file when running the instanceCatalog generator?

Are there other sqlite files to be concerned about?

**Comment by danielsf** [comment]
The AGN parameter database file can be specified using this command line argument

https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/master/bin.src/generateInstCat.py#L8

@jbkalmbach should confirm that the sprinkler does not use sqlite to access any of its data, but I believe that the AGN parameter database is the only sqlite file we use

**Comment by TomGlanzman** [comment]
Thanks @danielsf I should have discovered that myself.  But now that I am looking at the command invocation, there is also the opssim database, /global/projecta/projectdirs/lsst/groups/SSim/DC2/minion_1016_desc_dithered_v4.db.  Do you think it would be prudent to make a $SCRATCH copy of that one also?

**Comment by danielsf** [comment]
oh yeah... that

The OpSim database is about 4.5 GB in size.  Is staging that going to be more of a problem?

**Comment by jchiang87** [comment]
That's a substantially bigger file.  It is also only accessed once (or a few times at most) at the start of the instance catalog generation code.  I'm not sure how often the agn_db file is accessed, but I suspect it may be multiple times throughout the execution.  I would hold off on staging the opsim_db file until we see it being a problem.

**Comment by rbiswas4** [comment]
It should be possible to strip the opsim db to ~ few hundred MB (we don't need all the tables, summary ~ 800 MB, and we need a small area compared to all of it) for our purposes if this need arises but would be best to wait till this is known to be a problem.

**Comment by TomGlanzman** [comment]
As a first attempt, I am thinking of making a single copy of the sqlite file in Lustre($SCRATCH) to see if that solves the problem.  If not, then making a copy for each and every visit would be the next step.  For the moment, will leave the opsim DB as it is, although making a single copy in Lustre might be prudent.

**Comment by TomGlanzman** [comment]
I have made copies of both the agn and minion database files here:

/global/cscratch1/sd/descpho/Pipeline-tasks/DBstaging

and changed the workflow to use the new copies.  This should improve reliability/performance, but I do not know how much.  The change to the workflow config became effective as of 10:25 Pacific today.

**Comment by TomGlanzman** [comment]
I have seen no more instances of problems related to DB access in the instanceCatalog generation, so will consider this issue closed.  Thanks @jchiang87 and @danielsf !
